### ISSUE TITLE
Incompatible pointer types error

### ISSUE THREAD

**Issue by CasualRascal** [AyatanaIndicators/libayatana-indicator#24]
Can you replicate this error?
[libayatana-indicator-0.8.1.txt](https://github.com/AyatanaIndicators/libayatana-indicator/files/5131482/libayatana-indicator-0.8.1.txt)

**Comment by sunweaver** [comment]
@CasualRascal: Can you provide more context?

Against what GLib version are you building? What compiler version? On what distro? etc.

Thanks

**Comment by CasualRascal** [comment]
Hi, thank you for the reply,
GLib 2.63
clang 9.0.1
OpenMandriva Lx 4.1

**Comment by tari01** [comment]
@CasualRascal @sunweaver 

We now have automated builds using both `clang` and `gcc` - no failing builds on our side. Can we close this?

**Comment by sunweaver** [comment]
@CasualRascal: closing this one now, due to lack of feedback and unreproducibility as of today.
