### ISSUE TITLE
Update icons/schemas

### ISSUE THREAD

**Issue by tari01** [AyatanaIndicators/libayatana-indicator#30]
I am filing this for indicators in general, not this lib.

It would be very nice if each indicator's "make install" could call

`glib-compile-schemas /usr/share/glib-2.0/schemas`

and (if needed)

`gtk-update-icon-cache /usr/share/icons/hicolor`

**Comment by sunweaver** [comment]
urgh, wait...

This is normally package maintainer's business...

**Comment by tari01** [comment]
Makes sense, I will remove these from projects that have them. Closing.
