### ISSUE TITLE
Update debian/* and .travis.yml

### ISSUE THREAD

**Issue by tari01** [AyatanaIndicators/libayatana-indicator#39]
Depends https://github.com/AyatanaIndicators/libayatana-indicator/pull/38

**Comment by tari01** [comment]
@sunweaver `.build.yml` is now actually blocking #38. We need to make sure we run `clean` only once the tests have completed. It might even be a good idea to do this for all Ayatana components.

**Comment by sunweaver** [comment]
Resolved via 73e6c3aceb13b155c1f7af983acb8e7ed51e97c2 (changes in debian/rules, et al) and   bc6886f1c9021f167fc44a8f125059a8416e9b84 (.build.yml).
