### ISSUE TITLE
Are there any docs ?

### ISSUE THREAD

**Issue by davidbannon** [AyatanaIndicators/libayatana-indicator#45]
I am interested in Ayatana as Debian has declared it the replacement for libappindicator3 which, when used with gnome-shell-extension-appindicator provides a functional SysTray icon on a Gnome Desktop.

But when I look (in Synaptic) at Ayana-Indicator-datetime for example, it says that its only usable with desktops that provide a render for system indicators such as {mate, xfce, lom...}.  That sounds to me very much like its not going to work on Gnome Desktops. 

I have not been able to find any documention about how to use Ayatana, its API, example code, or where it actually does, or does not work.  Can you please point me in the right direction ?

Davo

**Comment by davidbannon** [comment]
Answering part of my own question ...

libayayana-appindicator3-dev does have an example ! In vala ??  In case someone else is as uninformed as I am about vala, compile it like this -

`valac --pkg gtk+-3.0 --pkg ayayana-appindicator3-0.1 ayayana-indicator-example.vala`

The "ayayana-appindicator3-0.1" is installed in /usr/share/vala by the above mentioned dev package.

And, wait for it, seems to work fine on bullseye with a Gnome Desktop.

Now, some object pascal bindings .....

Davo

**Comment by davidbannon** [comment]
In line with my practice of answering my own questions -
Where I said that it works fine with Bullseye Gnome, I should have added "as long as you have gnome-shell-extension-appindicator" installed AND enabled.  

As a stand alone solution, its fine on the nice desktops (but old SysTray usually works there anyway). And a replacement for libappindicator3 even on Gnome but with the same problem. Sigh. 

Object Pascal binding was easy anyway !

Thanks folks.


Davo

**Comment by tari01** [comment]
@davidbannon

By the time one of us finally got round to answer this, it appears you'd figured out everything :)

Can we close this?

**Comment by sunweaver** [comment]
@davidbannon I now close this issue. Reopen if not sufficiently answered or open a new issue, if more questions arise.
