### ISSUE TITLE
Indicators with IDO widgets freeze with Ubuntu's GTK-3

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/libayatana-indicator#8]
@tari01 

Now that we have...
https://github.com/AyatanaIndicators/libayatana-indicator/commit/b619354abad7662a8ad53d4885741d4d2ea8f4a0

I tried to install Ayatana Indicators on a Ubuntu 20.04 and I see freeze in the indicator panel whenever I click on a system indicator that is supposed to render special IDO widgets. Do you think that the above referenced commit might conflict with the indicator / IDO specific patch that Ubuntu's GTK has?

I will rebuild gtk-3 tomorrow / Wednesday on my Ubuntu test rig to see, if leaving out that one patch in Ubuntu's GTK fixes those freezes.

It would be nice, if you could work around this in libayatana-indicator itself (so that it tolerates Ubuntu's GMenu patch and does not choke on it).

**Comment by tari01** [comment]
Yes, it was to be expected. To be honest, I never thought someone would try this with a patched GTK. Using it with stock GTK will definitely work. We need to figure out a way to detect the hacked one and not call some parts of the code. (This is fun. We now want it not to work.)

**Comment by sunweaver** [comment]
Hi,

Am Montag, 10. August 2020 schrieb Robert Tari:
> Yes, it was to be expected. To be honest, I never thought someone would try this with a patched GTK. Using it with stock GTK will definitely work. We need to figure out a way to detect the hacked one and not call some parts of the code. (This is fun. We now want it not to work.) 
> 

How about renaming all those ido tags from x-canonical-foo to x-ayatana-foo. I wantef to do this in the first place, but didn't dare. Today, I know that I should have...

Mike

-- 
Gesendet von meinem Fairphone (powered by SailfishOS)

**Comment by tari01** [comment]
Ahead of you! I already thought of suggesting the name change a month ago - now we apparently have a good reason to do so.

**Comment by sunweaver** [comment]
Resolved via e34f12e2f496225c94111549f80e5f48ac3c9c1d.
